#!/bin/bash

USER="root"
PASSWORD="root"
OUTPUT="$HOME/mysql-backups"

mkdir $OUTPUT

#rm "$OUTPUTDIR/*gz" > /dev/null 2>&1

databases=`sudo mysql -u $USER -p$PASSWORD -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`

for db in $databases; do
    if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
        echo "Dumping database: $db"
	DATE=`date +%Y%m%d`
        sudo mysqldump -u $USER -p$PASSWORD --databases $db > $OUTPUT/$DATE.$db.sql
        gzip $OUTPUT/$DATE.$db.sql
	rm $OUTPUT/$DATE.$db.sql
    fi
done